/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Barang;
import backend.DBHelper;
import backend.TambahBaru;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abyan
 */
public class TambahBarangMasuk extends javax.swing.JFrame {

    /**
     * Creates new form TambahBaru
     */
    public TambahBarangMasuk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void tampilkanData(){
//        String[] kolom = {"kode_barang", "nama_barang", "satuan", "gudang_masuk", "gudang_keluar"};
//        ArrayList<TambahBaru> list = new TambahBaru().getAll();
//        Object rowData[] = new Object[5];
//        
//        jTable_BrngMsk.setModel(new DefaultTableModel(new Object[][] {}, kolom));
//        
//        for(int i =0; i<list.size(); i++){
//            rowData[0] = list.get(i).getKode_barang();
//            rowData[1] = list.get(i).getNama_barang();
//            rowData[2] = list.get(i).getSatuan();
//            rowData[3] = list.get(i).getGudang_masuk();
//            rowData[4] = list.get(i).getGudang_keluar();
//            
//            ((DefaultTableModel)jTable_BrngMsk.getModel()).addRow(rowData);
//        }
    }
    
     public void kosongkanForm(){
        TxtKodeBrg.setText("0");
        TxtNmaBrg.setText("");
        TxtQnty.setText("");
        TxtStn.setText("");
        TxtGdngMsk.setText("");
        TxtGdngKlr.setText("");
        TxtKtrng.setText("");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtKodeBrg = new javax.swing.JTextField();
        TxtNmaBrg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Btn_Smp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtStn = new javax.swing.JTextField();
        TxtGdngMsk = new javax.swing.JTextField();
        TxtGdngKlr = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TxtQnty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtKtrng = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel2.setText("Kode barang");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel3.setText("Nama Barang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setText("Satuan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel5.setText("Gudang Masuk");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel6.setText("Gudang Keluar");

        TxtKodeBrg.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        TxtKodeBrg.setName(""); // NOI18N
        TxtKodeBrg.setRequestFocusEnabled(false);
        TxtKodeBrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtKodeBrgMouseClicked(evt);
            }
        });
        TxtKodeBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodeBrgActionPerformed(evt);
            }
        });
        TxtKodeBrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtKodeBrgKeyPressed(evt);
            }
        });

        TxtNmaBrg.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        TxtNmaBrg.setName(""); // NOI18N
        TxtNmaBrg.setRequestFocusEnabled(false);
        TxtNmaBrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtNmaBrgMouseClicked(evt);
            }
        });
        TxtNmaBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNmaBrgActionPerformed(evt);
            }
        });
        TxtNmaBrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNmaBrgKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Btn_Smp.setText("Simpan");
        Btn_Smp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SmpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Tambah Baru");

        TxtStn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        TxtStn.setName(""); // NOI18N
        TxtStn.setRequestFocusEnabled(false);
        TxtStn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtStnMouseClicked(evt);
            }
        });
        TxtStn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStnActionPerformed(evt);
            }
        });

        TxtGdngMsk.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        TxtGdngMsk.setName(""); // NOI18N
        TxtGdngMsk.setRequestFocusEnabled(false);
        TxtGdngMsk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtGdngMskMouseClicked(evt);
            }
        });
        TxtGdngMsk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGdngMskActionPerformed(evt);
            }
        });

        TxtGdngKlr.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        TxtGdngKlr.setName(""); // NOI18N
        TxtGdngKlr.setRequestFocusEnabled(false);
        TxtGdngKlr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtGdngKlrMouseClicked(evt);
            }
        });
        TxtGdngKlr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGdngKlrActionPerformed(evt);
            }
        });

        TxtQnty.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        TxtQnty.setName(""); // NOI18N
        TxtQnty.setRequestFocusEnabled(false);
        TxtQnty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtQntyMouseClicked(evt);
            }
        });
        TxtQnty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtQntyActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel7.setText("Quantity");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel8.setText("Keterangan");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtQtyMouseClicked(evt);
            }
        });

        TxtKtrng.setColumns(20);
        TxtKtrng.setRows(5);
        TxtKtrng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtKtrngMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TxtKtrng);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Menu Awal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Barang Masuk");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Barang Keluar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setText("History");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Laporan Akhir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quit");

        MenuQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuQuit.setText("Quit");
        MenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuQuitActionPerformed(evt);
            }
        });
        jMenu2.add(MenuQuit);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Smp)
                        .addGap(193, 193, 193)
                        .addComponent(jButton1)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNmaBrg)
                    .addComponent(TxtKodeBrg)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addComponent(TxtStn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtGdngMsk)
                    .addComponent(TxtGdngKlr)
                    .addComponent(TxtQnty)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(TxtKodeBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TxtNmaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(TxtQnty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtStn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtGdngMsk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtGdngKlr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Btn_Smp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new MenuAwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new BarangMasuk().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new BarangKeluar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new HistoryBarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new LaporanAkhir().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void MenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuQuitActionPerformed
        // TODO add your handling code here:
        Object options[] = {"Ya", "Tidak"};
        int result = JOptionPane.showOptionDialog(this, "Apakah anda ingin keluar?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, options, options[1]);
        if(result == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuQuitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_SmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SmpActionPerformed
        if(TxtKodeBrg.getText().isEmpty()||TxtNmaBrg.getText().isEmpty()||TxtQnty.getText().isEmpty()||TxtStn.getText().isEmpty()||TxtGdngMsk.getText().isEmpty()||TxtGdngKlr.getText().isEmpty()||TxtKtrng.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data yang ditambahkan tidak boleh kosong!");
        }else{
            try{
                Statement st = DBHelper.getKoneksi().createStatement();
                int rs=st.executeUpdate("insert into tambahbarang values("
                    + "'"+TxtKodeBrg.getText()+"',"
                    + "'"+TxtNmaBrg.getText()+"',"
                    + "'"+TxtQnty.getText()+"',"
                    + "'"+TxtStn.getText()+"',"
                    + "'"+TxtGdngMsk.getText()+"',"
                    + "'"+TxtGdngKlr.getText()+"',"
                    + "'"+TxtKtrng.getText()
                    + "')"
                );
                st.close();
                bersih();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan...");
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Keterangan error : "+e);
            }
        }
        
//        Barang barang = new Barang();
//        if (TxtKodeBrg.getText().equals("")||TxtNmaBrg.getText().equals("")||TxtGdngMsk.getText().equals("")||TxtGdngKlr.getText().equals("")||TxtStn.getText().equals("")||TxtQnty.getText().equals("")||TxtKtrng.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "Field Harus Diisi Semua");
//        }else{
//        barang.setKode_barang(Integer.parseInt(TxtKodeBrg.getText()));
//        barang.setNama_barang(TxtNmaBrg.getText());
//        barang.setQty(Integer.parseInt(TxtQnty.getText()));
//        barang.setSatuan(TxtStn.getText());
//        barang.setGudang_masuk(TxtGdngMsk.getText());
//        barang.setGudang_keluar(TxtGdngKlr.getText());
//        barang.setKeterangan(TxtKtrng.getText());
////        barang.save();
//        
//        TxtKodeBrg.setText(Integer.toString(barang.getKode_barang()));
////        tampilkanData();
//        }
        
    }//GEN-LAST:event_Btn_SmpActionPerformed

    private void TxtKodeBrgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKodeBrgKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            TxtKodeBrg.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtKodeBrgKeyPressed

    private void TxtQtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtQtyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtQtyMouseClicked

    private void TxtNmaBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNmaBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNmaBrgActionPerformed

    private void TxtKodeBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodeBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKodeBrgActionPerformed

    private void TxtStnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStnActionPerformed

    private void TxtQntyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtQntyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtQntyActionPerformed

    private void TxtGdngMskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGdngMskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGdngMskActionPerformed

    private void TxtGdngKlrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGdngKlrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGdngKlrActionPerformed

    private void TxtKtrngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtKtrngMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKtrngMouseClicked

    private void TxtNmaBrgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNmaBrgKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            TxtNmaBrg.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtNmaBrgKeyPressed

    private void TxtQntyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtQntyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtQntyMouseClicked

    private void TxtNmaBrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNmaBrgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNmaBrgMouseClicked

    private void TxtStnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtStnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStnMouseClicked

    private void TxtKodeBrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtKodeBrgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKodeBrgMouseClicked

    private void TxtGdngMskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtGdngMskMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGdngMskMouseClicked

    private void TxtGdngKlrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtGdngKlrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGdngKlrMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahBarangMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Smp;
    private javax.swing.JMenuItem MenuQuit;
    private javax.swing.JTextField TxtGdngKlr;
    private javax.swing.JTextField TxtGdngMsk;
    public javax.swing.JTextField TxtKodeBrg;
    private javax.swing.JTextArea TxtKtrng;
    public static javax.swing.JTextField TxtNmaBrg;
    public static javax.swing.JTextField TxtQnty;
    private javax.swing.JTextField TxtStn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void bersih() {
        TxtKodeBrg.setText("");
        TxtNmaBrg.setText("");
        TxtQnty.setText("");
        TxtStn.setText("");
        TxtGdngMsk.setText("");
        TxtGdngKlr.setText("");
        TxtKtrng.setText("");
    }

}
